### ISSUE TITLE
Command line invokation using credentials for automation

### ISSUE THREAD

**Issue by techpavan** [refactorsaurusrex/easy-vpn#1]
I have a scenario in mind and would like to know if that is possible.
Bring up a web application which accepts the user's credentials and automatically connects the host to the VPN server. The host that contains the web application also would be running a proxy server and the client can make requests to any protected resource by setting the host as a proxy.

I haven't tried running easy-vpn, but by description, it seems like the password is entered via prompts which I believe is going to hinder automation attempts. In my scenario, the password would be RSA passcode and thus storing it securely is not really a requirement, but providing password as a part of initial input is.

**Comment by refactorsaurusrex** [comment]
I really have no idea. Sorry!
